### PR TITLE
Gazebo4

### PR DESCRIPTION
**Pull request by scpeters**
Fast-forward the gazebo branch.

Add tags for gazebo4 in 1b43338.

### CODE REVIEW

**Comment by ruffsl** [comment]
+1

**Comment by tfoote** [comment]
lgtm. 

@ruffsl So process check. We merge this here, and then submit a PR upstream to merge it there?

**Comment by ruffsl** [comment]
@tfoote , correct. Just make the PR to the official library like I did here:
https://github.com/docker-library/official-images/pull/855
with the added new tags, and a description of what's changed.

**Comment by tfoote** [comment]
upstream pr: https://github.com/docker-library/official-images/pull/971

**Pull request merged**
